
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    dataset.0.id: "example-dataset"
    dataset.0.useas: "mount"
spec:
    volumes:
    - name: example-dataset
      persistentVolumeClaim:
        claimName: example-dataset
    containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: example-dataset
          mountPath: "/mnt/data"

---

apiVersion: datashim.io/v1alpha1
kind: Dataset
metadata:
  name: example-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "access_key_id"
    secretAccessKey: "access_key"
    endpoint: "https://s3.ap-south-1.amazonaws.com"
    bucket: "bucket_name"
    readonly: "false" #OPTIONAL, default is false  
    region: "ap-south-1" #OPTIONAL